apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
  namespace: my-app
spec: 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
